//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elipgo.SmartClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elipgo.SmartClient.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #151515.
        /// </summary>
        internal static string color_background_container {
            get {
                return ResourceManager.GetString("color_background_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4285F4.
        /// </summary>
        internal static string color_container_selected {
            get {
                return ResourceManager.GetString("color_container_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #222222.
        /// </summary>
        internal static string color_gray_background {
            get {
                return ResourceManager.GetString("color_gray_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #313131.
        /// </summary>
        internal static string color_gray_context_menu {
            get {
                return ResourceManager.GetString("color_gray_context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #626262.
        /// </summary>
        internal static string color_gray_selected {
            get {
                return ResourceManager.GetString("color_gray_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3A3A3A.
        /// </summary>
        internal static string color_header_backcolor {
            get {
                return ResourceManager.GetString("color_header_backcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D3D3D3.
        /// </summary>
        internal static string color_title_font {
            get {
                return ResourceManager.GetString("color_title_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_app {
            get {
                object obj = ResourceManager.GetObject("icon_app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_camara_sidebar {
            get {
                object obj = ResourceManager.GetObject("icon_camara_sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_carruseles {
            get {
                object obj = ResourceManager.GetObject("icon_carruseles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_input_state_off {
            get {
                object obj = ResourceManager.GetObject("icon_input_state_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_input_state_on {
            get {
                object obj = ResourceManager.GetObject("icon_input_state_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_iot_entrada_sidebar {
            get {
                object obj = ResourceManager.GetObject("icon_iot_entrada_sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_iot_salida_sidebar {
            get {
                object obj = ResourceManager.GetObject("icon_iot_salida_sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_kpi {
            get {
                object obj = ResourceManager.GetObject("icon_kpi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_live {
            get {
                object obj = ResourceManager.GetObject("icon_live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_location {
            get {
                object obj = ResourceManager.GetObject("icon_location", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_planos {
            get {
                object obj = ResourceManager.GetObject("icon_planos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_playback {
            get {
                object obj = ResourceManager.GetObject("icon_playback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_seproban {
            get {
                object obj = ResourceManager.GetObject("icon_seproban", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_vault {
            get {
                object obj = ResourceManager.GetObject("icon_vault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_visual_search {
            get {
                object obj = ResourceManager.GetObject("icon_visual_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_avance_rapido {
            get {
                object obj = ResourceManager.GetObject("icons_avance_rapido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_bookmarks {
            get {
                object obj = ResourceManager.GetObject("icons_bookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_close {
            get {
                object obj = ResourceManager.GetObject("icons_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_full_screen {
            get {
                object obj = ResourceManager.GetObject("icons_full_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_guardias {
            get {
                object obj = ResourceManager.GetObject("icons_guardias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_mic_off {
            get {
                object obj = ResourceManager.GetObject("icons_mic_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_mic_on {
            get {
                object obj = ResourceManager.GetObject("icons_mic_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_pausa {
            get {
                object obj = ResourceManager.GetObject("icons_pausa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_play {
            get {
                object obj = ResourceManager.GetObject("icons_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_play_inverso {
            get {
                object obj = ResourceManager.GetObject("icons_play_inverso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_presets {
            get {
                object obj = ResourceManager.GetObject("icons_presets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_ptz {
            get {
                object obj = ResourceManager.GetObject("icons_ptz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_rec {
            get {
                object obj = ResourceManager.GetObject("icons_rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_rec_active {
            get {
                object obj = ResourceManager.GetObject("icons_rec_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_restroceso_rapido {
            get {
                object obj = ResourceManager.GetObject("icons_restroceso_rapido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_snapshot {
            get {
                object obj = ResourceManager.GetObject("icons_snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_sound_off {
            get {
                object obj = ResourceManager.GetObject("icons_sound_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_sound_on {
            get {
                object obj = ResourceManager.GetObject("icons_sound_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_live {
            get {
                object obj = ResourceManager.GetObject("logo_live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Sounds\siren-noise.mp3.
        /// </summary>
        internal static string path_alarm_sound {
            get {
                return ResourceManager.GetString("path_alarm_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Fonts\Roboto-Regular.ttf.
        /// </summary>
        internal static string path_font_roboto_regular {
            get {
                return ResourceManager.GetString("path_font_roboto_regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\app_context_bar\icon-carousel.png.
        /// </summary>
        internal static string path_icon_carousel {
            get {
                return ResourceManager.GetString("path_icon_carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\app_context_bar\icon-clear-grids.png.
        /// </summary>
        internal static string path_icon_clear_grids {
            get {
                return ResourceManager.GetString("path_icon_clear_grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\icon-filter.png.
        /// </summary>
        internal static string path_icon_filter {
            get {
                return ResourceManager.GetString("path_icon-filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\app_context_bar\icon-grids.png.
        /// </summary>
        internal static string path_icon_grids {
            get {
                return ResourceManager.GetString("path_icon_grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\app_context_bar\icon-groups.png.
        /// </summary>
        internal static string path_icon_groups {
            get {
                return ResourceManager.GetString("path_icon_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\app_context_bar\icon-scenes.png.
        /// </summary>
        internal static string path_icon_scenes {
            get {
                return ResourceManager.GetString("path_icon_scenes", resourceCulture);
            }
        }
    }
}
