//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elipgo.SmartClient.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VariableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elipgo.SmartClient.Common.Properties.VariableResources", typeof(VariableResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fe0000.
        /// </summary>
        public static string COLOR_ALARM_HIGH_LIGHT {
            get {
                return ResourceManager.GetString("COLOR_ALARM_HIGH_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        public static string COLOR_CONTAINER_BACKGROUND {
            get {
                return ResourceManager.GetString("COLOR_CONTAINER_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4285F4.
        /// </summary>
        public static string COLOR_CONTAINER_SELECTED {
            get {
                return ResourceManager.GetString("COLOR_CONTAINER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4285F4.
        /// </summary>
        public static string COLOR_CONTEXT {
            get {
                return ResourceManager.GetString("COLOR_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #222222.
        /// </summary>
        public static string COLOR_GRAY_BACKGROUND {
            get {
                return ResourceManager.GetString("COLOR_GRAY_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #313131.
        /// </summary>
        public static string COLOR_GRAY_CONTEXT_MENU {
            get {
                return ResourceManager.GetString("COLOR_GRAY_CONTEXT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #626262.
        /// </summary>
        public static string COLOR_GRAY_SELECTED {
            get {
                return ResourceManager.GetString("COLOR_GRAY_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3A3A3A.
        /// </summary>
        public static string COLOR_HEADER_BACKGROUND {
            get {
                return ResourceManager.GetString("COLOR_HEADER_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #222222.
        /// </summary>
        public static string COLOR_SWITCH_OFF {
            get {
                return ResourceManager.GetString("COLOR_SWITCH_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4285F4.
        /// </summary>
        public static string COLOR_SWITCH_ON {
            get {
                return ResourceManager.GetString("COLOR_SWITCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D3D3D3.
        /// </summary>
        public static string COLOR_TITLE_FONT {
            get {
                return ResourceManager.GetString("COLOR_TITLE_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string grid_maximum_quantity {
            get {
                return ResourceManager.GetString("grid_maximum_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1154.
        /// </summary>
        public static string live_button_location_x_references {
            get {
                return ResourceManager.GetString("live_button_location_x_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string live_button_location_y_references {
            get {
                return ResourceManager.GetString("live_button_location_y_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Sounds\siren-noise.wav.
        /// </summary>
        public static string PATH_ALARM_SOUND {
            get {
                return ResourceManager.GetString("PATH_ALARM_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Fonts\Roboto-Regular.ttf.
        /// </summary>
        public static string PATH_FONT_ROBOTO_REGULAR {
            get {
                return ResourceManager.GetString("PATH_FONT_ROBOTO_REGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Images\spinner.gif.
        /// </summary>
        public static string PATH_IMAGE_SPINNER {
            get {
                return ResourceManager.GetString("PATH_IMAGE_SPINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -48.
        /// </summary>
        public static string shift_location_x {
            get {
                return ResourceManager.GetString("shift_location_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string shift_location_y {
            get {
                return ResourceManager.GetString("shift_location_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartClientManual.pdf.
        /// </summary>
        public static string SmartClientManualPath {
            get {
                return ResourceManager.GetString("SmartClientManualPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string TRUNCATE {
            get {
                return ResourceManager.GetString("TRUNCATE", resourceCulture);
            }
        }
    }
}
