//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Elipgo.SmartClient.Drivers.PlayerService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PlayerServiceSoap", Namespace="http://ndvr.elipgo.com/player")]
    public partial class PlayerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestVideoPreParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestVideoPostParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PauseVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetVideoFramePositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetVideoTimePositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetVideoSkipRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVideoTimelineOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSmartSearchModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSmartSearchAreaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSmartSearchThresholdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSmartSearchOverlayOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartOfflineSmartSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback AbortOfflineSmartSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOfflineSmartSearchResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsOfflineSmartSearchCompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOfflineSmartSearchProgressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PlayerService() {
            this.Url = global::Elipgo.SmartClient.Drivers.Properties.Settings.Default.Elipgo_SmartClient_Drivers_PlayerService_PlayerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestVideoPreParameterCompletedEventHandler RequestVideoPreParameterCompleted;
        
        /// <remarks/>
        public event RequestVideoPostParameterCompletedEventHandler RequestVideoPostParameterCompleted;
        
        /// <remarks/>
        public event StartVideoCompletedEventHandler StartVideoCompleted;
        
        /// <remarks/>
        public event StopVideoCompletedEventHandler StopVideoCompleted;
        
        /// <remarks/>
        public event PauseVideoCompletedEventHandler PauseVideoCompleted;
        
        /// <remarks/>
        public event CloseVideoCompletedEventHandler CloseVideoCompleted;
        
        /// <remarks/>
        public event SetVideoFramePositionCompletedEventHandler SetVideoFramePositionCompleted;
        
        /// <remarks/>
        public event SetVideoTimePositionCompletedEventHandler SetVideoTimePositionCompleted;
        
        /// <remarks/>
        public event SetVideoSkipRateCompletedEventHandler SetVideoSkipRateCompleted;
        
        /// <remarks/>
        public event GetVideoTimelineCompletedEventHandler GetVideoTimelineCompleted;
        
        /// <remarks/>
        public event SetSmartSearchModeCompletedEventHandler SetSmartSearchModeCompleted;
        
        /// <remarks/>
        public event SetSmartSearchAreaCompletedEventHandler SetSmartSearchAreaCompleted;
        
        /// <remarks/>
        public event SetSmartSearchThresholdsCompletedEventHandler SetSmartSearchThresholdsCompleted;
        
        /// <remarks/>
        public event SetSmartSearchOverlayCompletedEventHandler SetSmartSearchOverlayCompleted;
        
        /// <remarks/>
        public event StartOfflineSmartSearchCompletedEventHandler StartOfflineSmartSearchCompleted;
        
        /// <remarks/>
        public event AbortOfflineSmartSearchCompletedEventHandler AbortOfflineSmartSearchCompleted;
        
        /// <remarks/>
        public event GetOfflineSmartSearchResultsCompletedEventHandler GetOfflineSmartSearchResultsCompleted;
        
        /// <remarks/>
        public event IsOfflineSmartSearchCompleteCompletedEventHandler IsOfflineSmartSearchCompleteCompleted;
        
        /// <remarks/>
        public event GetOfflineSmartSearchProgressCompletedEventHandler GetOfflineSmartSearchProgressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/RequestVideoPreParameter", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RequestVideoPreParameter(string cameraId, string dateTime, out int clientId, out int portTransfer) {
            object[] results = this.Invoke("RequestVideoPreParameter", new object[] {
                        cameraId,
                        dateTime});
            clientId = ((int)(results[1]));
            portTransfer = ((int)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequestVideoPreParameterAsync(string cameraId, string dateTime) {
            this.RequestVideoPreParameterAsync(cameraId, dateTime, null);
        }
        
        /// <remarks/>
        public void RequestVideoPreParameterAsync(string cameraId, string dateTime, object userState) {
            if ((this.RequestVideoPreParameterOperationCompleted == null)) {
                this.RequestVideoPreParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestVideoPreParameterOperationCompleted);
            }
            this.InvokeAsync("RequestVideoPreParameter", new object[] {
                        cameraId,
                        dateTime}, this.RequestVideoPreParameterOperationCompleted, userState);
        }
        
        private void OnRequestVideoPreParameterOperationCompleted(object arg) {
            if ((this.RequestVideoPreParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestVideoPreParameterCompleted(this, new RequestVideoPreParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/RequestVideoPostParameter", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RequestVideoPostParameter(int clientId, string cameraId, out int frameCount, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] out byte[] timeLine, out string name) {
            object[] results = this.Invoke("RequestVideoPostParameter", new object[] {
                        clientId,
                        cameraId});
            frameCount = ((int)(results[1]));
            timeLine = ((byte[])(results[2]));
            name = ((string)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequestVideoPostParameterAsync(int clientId, string cameraId) {
            this.RequestVideoPostParameterAsync(clientId, cameraId, null);
        }
        
        /// <remarks/>
        public void RequestVideoPostParameterAsync(int clientId, string cameraId, object userState) {
            if ((this.RequestVideoPostParameterOperationCompleted == null)) {
                this.RequestVideoPostParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestVideoPostParameterOperationCompleted);
            }
            this.InvokeAsync("RequestVideoPostParameter", new object[] {
                        clientId,
                        cameraId}, this.RequestVideoPostParameterOperationCompleted, userState);
        }
        
        private void OnRequestVideoPostParameterOperationCompleted(object arg) {
            if ((this.RequestVideoPostParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestVideoPostParameterCompleted(this, new RequestVideoPostParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/StartVideo", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartVideo(int clientId) {
            this.Invoke("StartVideo", new object[] {
                        clientId});
        }
        
        /// <remarks/>
        public void StartVideoAsync(int clientId) {
            this.StartVideoAsync(clientId, null);
        }
        
        /// <remarks/>
        public void StartVideoAsync(int clientId, object userState) {
            if ((this.StartVideoOperationCompleted == null)) {
                this.StartVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartVideoOperationCompleted);
            }
            this.InvokeAsync("StartVideo", new object[] {
                        clientId}, this.StartVideoOperationCompleted, userState);
        }
        
        private void OnStartVideoOperationCompleted(object arg) {
            if ((this.StartVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartVideoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/StopVideo", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StopVideo(int clientId) {
            this.Invoke("StopVideo", new object[] {
                        clientId});
        }
        
        /// <remarks/>
        public void StopVideoAsync(int clientId) {
            this.StopVideoAsync(clientId, null);
        }
        
        /// <remarks/>
        public void StopVideoAsync(int clientId, object userState) {
            if ((this.StopVideoOperationCompleted == null)) {
                this.StopVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopVideoOperationCompleted);
            }
            this.InvokeAsync("StopVideo", new object[] {
                        clientId}, this.StopVideoOperationCompleted, userState);
        }
        
        private void OnStopVideoOperationCompleted(object arg) {
            if ((this.StopVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopVideoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/PauseVideo", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PauseVideo(int clientId) {
            this.Invoke("PauseVideo", new object[] {
                        clientId});
        }
        
        /// <remarks/>
        public void PauseVideoAsync(int clientId) {
            this.PauseVideoAsync(clientId, null);
        }
        
        /// <remarks/>
        public void PauseVideoAsync(int clientId, object userState) {
            if ((this.PauseVideoOperationCompleted == null)) {
                this.PauseVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPauseVideoOperationCompleted);
            }
            this.InvokeAsync("PauseVideo", new object[] {
                        clientId}, this.PauseVideoOperationCompleted, userState);
        }
        
        private void OnPauseVideoOperationCompleted(object arg) {
            if ((this.PauseVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PauseVideoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/CloseVideo", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CloseVideo(int clientId) {
            this.Invoke("CloseVideo", new object[] {
                        clientId});
        }
        
        /// <remarks/>
        public void CloseVideoAsync(int clientId) {
            this.CloseVideoAsync(clientId, null);
        }
        
        /// <remarks/>
        public void CloseVideoAsync(int clientId, object userState) {
            if ((this.CloseVideoOperationCompleted == null)) {
                this.CloseVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseVideoOperationCompleted);
            }
            this.InvokeAsync("CloseVideo", new object[] {
                        clientId}, this.CloseVideoOperationCompleted, userState);
        }
        
        private void OnCloseVideoOperationCompleted(object arg) {
            if ((this.CloseVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseVideoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetVideoFramePosition", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetVideoFramePosition(int clientId, int position) {
            this.Invoke("SetVideoFramePosition", new object[] {
                        clientId,
                        position});
        }
        
        /// <remarks/>
        public void SetVideoFramePositionAsync(int clientId, int position) {
            this.SetVideoFramePositionAsync(clientId, position, null);
        }
        
        /// <remarks/>
        public void SetVideoFramePositionAsync(int clientId, int position, object userState) {
            if ((this.SetVideoFramePositionOperationCompleted == null)) {
                this.SetVideoFramePositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetVideoFramePositionOperationCompleted);
            }
            this.InvokeAsync("SetVideoFramePosition", new object[] {
                        clientId,
                        position}, this.SetVideoFramePositionOperationCompleted, userState);
        }
        
        private void OnSetVideoFramePositionOperationCompleted(object arg) {
            if ((this.SetVideoFramePositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetVideoFramePositionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetVideoTimePosition", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetVideoTimePosition(int clientId, string seekDateTime) {
            this.Invoke("SetVideoTimePosition", new object[] {
                        clientId,
                        seekDateTime});
        }
        
        /// <remarks/>
        public void SetVideoTimePositionAsync(int clientId, string seekDateTime) {
            this.SetVideoTimePositionAsync(clientId, seekDateTime, null);
        }
        
        /// <remarks/>
        public void SetVideoTimePositionAsync(int clientId, string seekDateTime, object userState) {
            if ((this.SetVideoTimePositionOperationCompleted == null)) {
                this.SetVideoTimePositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetVideoTimePositionOperationCompleted);
            }
            this.InvokeAsync("SetVideoTimePosition", new object[] {
                        clientId,
                        seekDateTime}, this.SetVideoTimePositionOperationCompleted, userState);
        }
        
        private void OnSetVideoTimePositionOperationCompleted(object arg) {
            if ((this.SetVideoTimePositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetVideoTimePositionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetVideoSkipRate", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetVideoSkipRate(int clientId, int rate) {
            this.Invoke("SetVideoSkipRate", new object[] {
                        clientId,
                        rate});
        }
        
        /// <remarks/>
        public void SetVideoSkipRateAsync(int clientId, int rate) {
            this.SetVideoSkipRateAsync(clientId, rate, null);
        }
        
        /// <remarks/>
        public void SetVideoSkipRateAsync(int clientId, int rate, object userState) {
            if ((this.SetVideoSkipRateOperationCompleted == null)) {
                this.SetVideoSkipRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetVideoSkipRateOperationCompleted);
            }
            this.InvokeAsync("SetVideoSkipRate", new object[] {
                        clientId,
                        rate}, this.SetVideoSkipRateOperationCompleted, userState);
        }
        
        private void OnSetVideoSkipRateOperationCompleted(object arg) {
            if ((this.SetVideoSkipRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetVideoSkipRateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/GetVideoTimeline", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetVideoTimeline(int clientId) {
            object[] results = this.Invoke("GetVideoTimeline", new object[] {
                        clientId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVideoTimelineAsync(int clientId) {
            this.GetVideoTimelineAsync(clientId, null);
        }
        
        /// <remarks/>
        public void GetVideoTimelineAsync(int clientId, object userState) {
            if ((this.GetVideoTimelineOperationCompleted == null)) {
                this.GetVideoTimelineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVideoTimelineOperationCompleted);
            }
            this.InvokeAsync("GetVideoTimeline", new object[] {
                        clientId}, this.GetVideoTimelineOperationCompleted, userState);
        }
        
        private void OnGetVideoTimelineOperationCompleted(object arg) {
            if ((this.GetVideoTimelineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVideoTimelineCompleted(this, new GetVideoTimelineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetSmartSearchMode", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSmartSearchMode(int id, bool enable) {
            this.Invoke("SetSmartSearchMode", new object[] {
                        id,
                        enable});
        }
        
        /// <remarks/>
        public void SetSmartSearchModeAsync(int id, bool enable) {
            this.SetSmartSearchModeAsync(id, enable, null);
        }
        
        /// <remarks/>
        public void SetSmartSearchModeAsync(int id, bool enable, object userState) {
            if ((this.SetSmartSearchModeOperationCompleted == null)) {
                this.SetSmartSearchModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSmartSearchModeOperationCompleted);
            }
            this.InvokeAsync("SetSmartSearchMode", new object[] {
                        id,
                        enable}, this.SetSmartSearchModeOperationCompleted, userState);
        }
        
        private void OnSetSmartSearchModeOperationCompleted(object arg) {
            if ((this.SetSmartSearchModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSmartSearchModeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetSmartSearchArea", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSmartSearchArea(int id, int left, int top, int width, int height) {
            this.Invoke("SetSmartSearchArea", new object[] {
                        id,
                        left,
                        top,
                        width,
                        height});
        }
        
        /// <remarks/>
        public void SetSmartSearchAreaAsync(int id, int left, int top, int width, int height) {
            this.SetSmartSearchAreaAsync(id, left, top, width, height, null);
        }
        
        /// <remarks/>
        public void SetSmartSearchAreaAsync(int id, int left, int top, int width, int height, object userState) {
            if ((this.SetSmartSearchAreaOperationCompleted == null)) {
                this.SetSmartSearchAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSmartSearchAreaOperationCompleted);
            }
            this.InvokeAsync("SetSmartSearchArea", new object[] {
                        id,
                        left,
                        top,
                        width,
                        height}, this.SetSmartSearchAreaOperationCompleted, userState);
        }
        
        private void OnSetSmartSearchAreaOperationCompleted(object arg) {
            if ((this.SetSmartSearchAreaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSmartSearchAreaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetSmartSearchThresholds", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSmartSearchThresholds(int id, int delta, int vol) {
            this.Invoke("SetSmartSearchThresholds", new object[] {
                        id,
                        delta,
                        vol});
        }
        
        /// <remarks/>
        public void SetSmartSearchThresholdsAsync(int id, int delta, int vol) {
            this.SetSmartSearchThresholdsAsync(id, delta, vol, null);
        }
        
        /// <remarks/>
        public void SetSmartSearchThresholdsAsync(int id, int delta, int vol, object userState) {
            if ((this.SetSmartSearchThresholdsOperationCompleted == null)) {
                this.SetSmartSearchThresholdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSmartSearchThresholdsOperationCompleted);
            }
            this.InvokeAsync("SetSmartSearchThresholds", new object[] {
                        id,
                        delta,
                        vol}, this.SetSmartSearchThresholdsOperationCompleted, userState);
        }
        
        private void OnSetSmartSearchThresholdsOperationCompleted(object arg) {
            if ((this.SetSmartSearchThresholdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSmartSearchThresholdsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/SetSmartSearchOverlay", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSmartSearchOverlay(int id, bool show, int red, int green, int blue) {
            this.Invoke("SetSmartSearchOverlay", new object[] {
                        id,
                        show,
                        red,
                        green,
                        blue});
        }
        
        /// <remarks/>
        public void SetSmartSearchOverlayAsync(int id, bool show, int red, int green, int blue) {
            this.SetSmartSearchOverlayAsync(id, show, red, green, blue, null);
        }
        
        /// <remarks/>
        public void SetSmartSearchOverlayAsync(int id, bool show, int red, int green, int blue, object userState) {
            if ((this.SetSmartSearchOverlayOperationCompleted == null)) {
                this.SetSmartSearchOverlayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSmartSearchOverlayOperationCompleted);
            }
            this.InvokeAsync("SetSmartSearchOverlay", new object[] {
                        id,
                        show,
                        red,
                        green,
                        blue}, this.SetSmartSearchOverlayOperationCompleted, userState);
        }
        
        private void OnSetSmartSearchOverlayOperationCompleted(object arg) {
            if ((this.SetSmartSearchOverlayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSmartSearchOverlayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/StartOfflineSmartSearch", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartOfflineSmartSearch(string cameraId, string start, string end, int deltaSeconds, int roiX, int roiY, int roiW, int roiH, int thDelta, int thVol) {
            this.Invoke("StartOfflineSmartSearch", new object[] {
                        cameraId,
                        start,
                        end,
                        deltaSeconds,
                        roiX,
                        roiY,
                        roiW,
                        roiH,
                        thDelta,
                        thVol});
        }
        
        /// <remarks/>
        public void StartOfflineSmartSearchAsync(string cameraId, string start, string end, int deltaSeconds, int roiX, int roiY, int roiW, int roiH, int thDelta, int thVol) {
            this.StartOfflineSmartSearchAsync(cameraId, start, end, deltaSeconds, roiX, roiY, roiW, roiH, thDelta, thVol, null);
        }
        
        /// <remarks/>
        public void StartOfflineSmartSearchAsync(string cameraId, string start, string end, int deltaSeconds, int roiX, int roiY, int roiW, int roiH, int thDelta, int thVol, object userState) {
            if ((this.StartOfflineSmartSearchOperationCompleted == null)) {
                this.StartOfflineSmartSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartOfflineSmartSearchOperationCompleted);
            }
            this.InvokeAsync("StartOfflineSmartSearch", new object[] {
                        cameraId,
                        start,
                        end,
                        deltaSeconds,
                        roiX,
                        roiY,
                        roiW,
                        roiH,
                        thDelta,
                        thVol}, this.StartOfflineSmartSearchOperationCompleted, userState);
        }
        
        private void OnStartOfflineSmartSearchOperationCompleted(object arg) {
            if ((this.StartOfflineSmartSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartOfflineSmartSearchCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/AbortOfflineSmartSearch", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AbortOfflineSmartSearch() {
            this.Invoke("AbortOfflineSmartSearch", new object[0]);
        }
        
        /// <remarks/>
        public void AbortOfflineSmartSearchAsync() {
            this.AbortOfflineSmartSearchAsync(null);
        }
        
        /// <remarks/>
        public void AbortOfflineSmartSearchAsync(object userState) {
            if ((this.AbortOfflineSmartSearchOperationCompleted == null)) {
                this.AbortOfflineSmartSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAbortOfflineSmartSearchOperationCompleted);
            }
            this.InvokeAsync("AbortOfflineSmartSearch", new object[0], this.AbortOfflineSmartSearchOperationCompleted, userState);
        }
        
        private void OnAbortOfflineSmartSearchOperationCompleted(object arg) {
            if ((this.AbortOfflineSmartSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AbortOfflineSmartSearchCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/GetOfflineSmartSearchResults", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetOfflineSmartSearchResults() {
            object[] results = this.Invoke("GetOfflineSmartSearchResults", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOfflineSmartSearchResultsAsync() {
            this.GetOfflineSmartSearchResultsAsync(null);
        }
        
        /// <remarks/>
        public void GetOfflineSmartSearchResultsAsync(object userState) {
            if ((this.GetOfflineSmartSearchResultsOperationCompleted == null)) {
                this.GetOfflineSmartSearchResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfflineSmartSearchResultsOperationCompleted);
            }
            this.InvokeAsync("GetOfflineSmartSearchResults", new object[0], this.GetOfflineSmartSearchResultsOperationCompleted, userState);
        }
        
        private void OnGetOfflineSmartSearchResultsOperationCompleted(object arg) {
            if ((this.GetOfflineSmartSearchResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfflineSmartSearchResultsCompleted(this, new GetOfflineSmartSearchResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/IsOfflineSmartSearchComplete", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsOfflineSmartSearchComplete() {
            object[] results = this.Invoke("IsOfflineSmartSearchComplete", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsOfflineSmartSearchCompleteAsync() {
            this.IsOfflineSmartSearchCompleteAsync(null);
        }
        
        /// <remarks/>
        public void IsOfflineSmartSearchCompleteAsync(object userState) {
            if ((this.IsOfflineSmartSearchCompleteOperationCompleted == null)) {
                this.IsOfflineSmartSearchCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOfflineSmartSearchCompleteOperationCompleted);
            }
            this.InvokeAsync("IsOfflineSmartSearchComplete", new object[0], this.IsOfflineSmartSearchCompleteOperationCompleted, userState);
        }
        
        private void OnIsOfflineSmartSearchCompleteOperationCompleted(object arg) {
            if ((this.IsOfflineSmartSearchCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOfflineSmartSearchCompleteCompleted(this, new IsOfflineSmartSearchCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ndvr.elipgo.com/player/GetOfflineSmartSearchProgress", RequestNamespace="http://ndvr.elipgo.com/player", ResponseNamespace="http://ndvr.elipgo.com/player", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetOfflineSmartSearchProgress() {
            object[] results = this.Invoke("GetOfflineSmartSearchProgress", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetOfflineSmartSearchProgressAsync() {
            this.GetOfflineSmartSearchProgressAsync(null);
        }
        
        /// <remarks/>
        public void GetOfflineSmartSearchProgressAsync(object userState) {
            if ((this.GetOfflineSmartSearchProgressOperationCompleted == null)) {
                this.GetOfflineSmartSearchProgressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfflineSmartSearchProgressOperationCompleted);
            }
            this.InvokeAsync("GetOfflineSmartSearchProgress", new object[0], this.GetOfflineSmartSearchProgressOperationCompleted, userState);
        }
        
        private void OnGetOfflineSmartSearchProgressOperationCompleted(object arg) {
            if ((this.GetOfflineSmartSearchProgressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfflineSmartSearchProgressCompleted(this, new GetOfflineSmartSearchProgressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RequestVideoPreParameterCompletedEventHandler(object sender, RequestVideoPreParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestVideoPreParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestVideoPreParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int clientId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int portTransfer {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RequestVideoPostParameterCompletedEventHandler(object sender, RequestVideoPostParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestVideoPostParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestVideoPostParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int frameCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public byte[] timeLine {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void StartVideoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void StopVideoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PauseVideoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CloseVideoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetVideoFramePositionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetVideoTimePositionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetVideoSkipRateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetVideoTimelineCompletedEventHandler(object sender, GetVideoTimelineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVideoTimelineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVideoTimelineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetSmartSearchModeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetSmartSearchAreaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetSmartSearchThresholdsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetSmartSearchOverlayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void StartOfflineSmartSearchCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AbortOfflineSmartSearchCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetOfflineSmartSearchResultsCompletedEventHandler(object sender, GetOfflineSmartSearchResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfflineSmartSearchResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfflineSmartSearchResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsOfflineSmartSearchCompleteCompletedEventHandler(object sender, IsOfflineSmartSearchCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsOfflineSmartSearchCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOfflineSmartSearchCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetOfflineSmartSearchProgressCompletedEventHandler(object sender, GetOfflineSmartSearchProgressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfflineSmartSearchProgressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfflineSmartSearchProgressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591